# Generated by Django 2.1.1 on 2018-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180924_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
