# Generated by Django 2.1.1 on 2018-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_field_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='polygon',
            field=models.CharField(default='', max_length=250),
        ),
    ]
