# Generated by Django 2.1.1 on 2018-11-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20181031_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedDate', models.DateField(auto_now_add=True)),
                ('harvestDate', models.DateField(auto_now=True)),
                ('field', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Field')),
            ],
        ),
    ]
