# Generated by Django 2.1.1 on 2018-11-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_seedprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='cultureID',
        ),
        migrations.RemoveField(
            model_name='field',
            name='process',
        ),
        migrations.AlterField(
            model_name='field',
            name='polygon',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='seedprocess',
            name='harvestDate',
            field=models.DateField(),
        ),
    ]
