# Generated by Django 2.1.1 on 2018-11-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20181104_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.RemoveField(
            model_name='seedprocess',
            name='field',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='SeedProcess',
        ),
    ]
