# Generated by Django 2.1.1 on 2018-11-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0008_auto_20181104_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('color', models.CharField(default='#cccccc', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('square', models.FloatField()),
                ('polygon', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeedProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedDate', models.DateField(auto_now_add=True)),
                ('harvestDate', models.DateField()),
                ('culture', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Culture')),
                ('field', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Field')),
            ],
        ),
    ]
